--PERCENT TYPE
--MANTER O HARDCODE ENTRE O PLSQL E A PROPRIA TABELA, SEM PRECISAR ESPECIFICAR QUAL TIPO DE DADO OU ATÉ MESMO A QTDE


DECLARE 

    v_ID segmercado.ID%type :=3;
    v_DESCRICAO segmercado.DESCRICAO%type := 'Industria';
    
BEGIN
    INSERT INTO segmercado(ID, DESCRICAO) VALUES(v_ID, v_DESCRICAO);
    COMMIT;

END;
